version: '3'

services:
  db:
    build: ./db
    tty: true
    container_name: db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "comauth_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always

  web:
    build:
      context: ./web
      #      args:
      #        - HTTPS=${HTTPS}
      #        - ENVIRONMENT=${ENVIRONMENT}
    tty: true
    container_name: web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - "./web/admin:/var/comauth/admin:z"
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always

volumes:
  comauth_data:
      driver: local
