version: '3'

services:
  ums-db:
    build: ./docker/db
    tty: true
    container_name: ums-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    volumes:
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "comauth_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always

  ums-admin:
    build:
      context: ./docker/web
    tty: true
    container_name: umg-admin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - "./app:/var/comauth/admin:z"
    depends_on:
      - ums-db
    ports:
      - "80:80"
    restart: always

volumes:
  comauth_data:
      driver: local
