name: e2e

on:
  pull_request:
    branches: [master]

jobs:
  #   ie:
  #     runs-on: windows-latest
  #     steps:
  #       - uses: actions/checkout@v1
  #       - uses: warrenbuckley/Setup-Nuget@v1
  #       - uses: actions/setup-node@v1
  #         with:
  #           node-version: 12
  #       - run: yarn install
  #       - run: yarn add selenium-webdriver
  #       - run: nuget install Selenium.WebDriver.IEDriver -Version 3.150.0
  #       - run: node scratch.js
  #         env:
  #           BROWSER: ie
  # firefox:
  #   runs-on: ubuntu-latest
  #   services:
  #     selenium:
  #       image: selenium/standalone-firefox
  #       ports:
  #         - 4444:4444
  #       volumes:
  #         - /dev/shm:/dev/shm
  #       options: "--name selenium"
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: chmod 777 app/log
  #     - run: cd app/config && ln -s config_local.php config.php && ls -la
  #     - run: docker-compose up -d --build
  #     - run: yarn install
  #     - run: yarn add mocha moment selenium-webdriver
  #     - run: docker network connect ums-admin_default selenium
  #     - run: sleep 30
  #     - run: docker ps -a
  #     - run: yarn mocha test/e2e/src/app/index.js --timeout 3600000
  #       env:
  #         BROWSER: firefox
  #         CI: true
  chrome:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:87.0
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
          - /tmp/download:/tmp/download
        options: "--name selenium"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup env
        run: |
          chmod 777 app/log
          cd app/config && ln -s config_local.php config.php && ls -la
          docker-compose up -d --build

      - name: e2e test
        working-directory: ./test/e2e/script
        run: |
          yarn install
          sudo chmod 777 /tmp/download && ls -la /tmp
          docker network connect ums-admin_default selenium
          sleep 30
          docker ps -a
          yarn lint
          yarn test
        env:
          BROWSER: chrome
          CI: true